# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9200
  servlet:
    context-path: /lvyuan

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  application:
    name: lvyuan-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
