#server:
#  port: 88
#
#spring:
#  application:
#    name: lvyuan-getway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        namespace: ad5ed1b1-bd1c-4fa1-9bc2-5c0e2c24b638
#    gateway:
#      routes:
#        - id: test_route
#          uri: https://www.baidu.com
#          predicates:
#            - Query=url,baidu
#
#        - id: qq_route
#          uri: https://www.qq.com
#          predicates:
#            - Query=url,qq
#
#        - id: bilibili_route
#          uri: https://www.bilibili.com
#          predicates:
#            - Query=url,bilibili
