# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9091
  servlet:
    context-path: /lvyuan

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
